version: '3'

services:

  cloudsql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.15
    entrypoint: ['/cloud_sql_proxy']
    command:
    - -instances=${CLOUDSQL_CONNECTION_STRING}=tcp:0.0.0.0:3306
    - -credential_file=/secrets/cloudsql/credentials.json
    - -dir=/cloudsql
    volumes:
    - ./private/credentials/cloudsql-credentials.json:/secrets/cloudsql/credentials.json

  mysqldump:
    build: .
    entrypoint: ['/usr/local/bin/db-dump']
    #entrypoint: ['sleep', '9999']
    env_file:
      - .env
    volumes:
    - ./private/credentials/bucket-credentials.json:/secrets/bucket/credentials.json
    - ./private/tables.txt:/config/tables.txt
    - ./private/data:/data
    - ./private/repos:/home/mintel/.config/backup/restic/repos
    - ./private/sets:/home/mintel/.config/backup/restic/sets
